# fly.toml app configuration file generated for tourney on 2025-05-12T01:38:47+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'tourney'
primary_region = 'sin'
console_command = 'php /var/www/html/artisan tinker'

[build]
  image = 'ghcr.io/creasico/project-tourney:main'
  ignorefile = '.deploy/production/Dockerfile.dockerignore'

[deploy]
  release_command = 'php /var/www/html/artisan migrate --force'

[env]
  APP_ENV = 'staging'
  APP_FAKER_LOCALE = 'id_ID'
  APP_LOCALE = 'id'
  APP_NAME = 'Tourney'
  DB_CONNECTION = 'pgsql'
  CACHE_STORE = 'redis'
  LOG_CHANNEL = 'stack'
  LOG_LEVEL = 'info'
  LOG_STACK = 'stderr,sentry'
  LOG_STDERR_FORMATTER = 'Monolog\Formatter\JsonFormatter'
  QUEUE_CONNECTION = 'redis'
  SESSION_DRIVER = 'redis'
  SESSION_SECURE_COOKIE = 'true'
  SENTRY_PROFILING_ENABLE = 'true'

[[mounts]]
  source = 'tourney'
  destination = '/var/www/html/storage/app'
  processes = ['app']

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512MB'
  cpu_kind = 'shared'
  cpus = 1
