name: Docker
run-name: 'build(docker): image for `${{ github.ref_name }}`'

on:
  # push:
  #   branches: [main]
  # workflow_call:
  workflow_run:
    workflows: [Code Quality]
    types: [completed]
    branches: [main]

jobs:
  prepare:
    name: Prepare
    uses: projek-xyz/actions/.github/workflows/configure.yml@main

  build:
    name: Build
    needs: prepare
    uses: projek-xyz/actions/.github/workflows/build.yml@main
    secrets:
      ACCESS_TOKEN: ${{ secrets.PAT }}
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
    with:
      branch: ${{ needs.prepare.outputs.target-branch }}
      composer-cache: ${{ needs.prepare.outputs.composer-cache-dir }}
      composer-cache-key: ${{ needs.prepare.outputs.composer-cache-key }}
      sentry-project: ${{ vars.SENTRY_PROJECT }}
      target-env: staging

  image:
    name: Image
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    needs: build

    permissions:
      contents: read
      packages: write

    env:
      IMAGE_REGISTRY: ghcr.io
      IMAGE_NAME: creasico/project-tourney

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Download assets
        uses: actions/download-artifact@v5
        with:
          name: build-staging
          path: public

      - name: Login to ${{ env.IMAGE_REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN  }}

      - name: Generate meta data
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm64
          file: .deploy/production/Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
